forge "https://forgeapi.puppetlabs.com"
mod 'attachmentgenie/puppetmaster',
  :git => "git://github.com/attachmentgenie/attachmentgenie-puppetmaster.git"
mod 'croddy/make'
mod 'gentoo/portage'
mod 'jfryman/selinux'
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat', '1.2.2'
mod 'puppetlabs/firewall'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/haproxy'
mod 'puppetlabs/inifile'
mod 'puppetlabs/ntp'
mod 'puppetlabs/pe_gem'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod 'stahnma/epel'
mod 'theforeman/concat_native'
mod 'theforeman/puppet'
mod 'zack/r10k'
